spring:
  application:
    name: springcloudRibbon
server:
  port: 5007
feign:
  hystrix:
    #是否启动hystrix
    enabled: true
  client:
    config:
      default:
        #fegin的超时时间
        connectTimeout: 2000
        readTimeout: 2000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:5000/eureka/
hystrix:
  command:
    default:
      execution:
        timeout:
          #如果enabled设置为false，则请求超时交给ribbon控制,为true,则超时作为熔断根据
          enable: true
        isolation:
          thread:
            timeoutInMilliseconds: 2000