spring:
  application:
    name: springbootService
  cloud:
    config:
      uri: http://localhost:6002/
      profile: release
server:
  port: 6006
security:
  basic:
    enabled: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:5000/eureka/
