server:
  port: 5000
eureka:
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
  client:
    #是否向服务注册中心注册自己,默认为true
    register-with-eureka: false
    #是否检索服务
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    registry-fetch-interval-seconds: 30
logging:
  level:
    org.springframework: debug
  file: ./logs/haos-config.log
  file.max-size: 100MB